# config.yaml
data:
  path: "data/raw/mnist.csv"
  augmentation_percentages:
  - 0.05
  - 0.10
  - 0.15

results:
  plots_dir: "results/plots"
  model_dir: "results/models"

training:
  epochs: 50
  batch_size: 32
  early_stopping_patience: 5
  learning_rate: 0.001
  validation_split: 0.2
